# Generated by Django 5.1.7 on 2025-04-07 11:56

import pgvector.django.vector
from pgvector.django import VectorExtension
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="VectorEmbeddings",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("videofile", models.FileField(upload_to="video/%y")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=512, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "managed": True,
            },
        ),
    ]
